
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 28 02:58:34 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 31;
  public static final int MULT = 16;
  public static final int CONST = 40;
  public static final int EQ_TO = 20;
  public static final int NUMCONST = 34;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 17;
  public static final int STATIC = 43;
  public static final int GREQ = 23;
  public static final int RPAREN = 7;
  public static final int AND = 26;
  public static final int RANGE = 14;
  public static final int OR = 27;
  public static final int COMMA = 11;
  public static final int NEQ_TO = 21;
  public static final int INC = 28;
  public static final int DIV = 18;
  public static final int PLUS = 10;
  public static final int IF = 38;
  public static final int DOT = 33;
  public static final int LE = 24;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 32;
  public static final int EQUAL = 8;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MOD = 19;
  public static final int IDENT = 36;
  public static final int VOID = 13;
  public static final int COLON = 30;
  public static final int ELSE = 39;
  public static final int LBRACE = 3;
  public static final int READ = 42;
  public static final int CHARCONST = 35;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 37;
  public static final int PROG = 2;
  public static final int LEQ = 25;
  public static final int HASHTAG = 15;
  public static final int DEC = 29;
  public static final int GR = 22;
  public static final int PRINT = 12;
}

